export { default as Home } from './home';
export * as Dashboard from './dashboard';
export { default as TestExam } from './testExam';
export { default as Exercises } from './exercise';
export { default as ExerciseQuiz } from './exercise/ExerciseQuiz';
export { default as Result } from './result';
export { default as ResultProgress } from './result/ResultProgress';
export { default as SignIn } from './signIn';
export { default as SignUp } from './signUp';
export { default as NotFound } from './404';